Survey::Option.create!([
  {question_id: 1, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 1, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 1, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 1, weight: 4, text: "AGREE", correct: nil},
  {question_id: 1, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 2, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 2, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 2, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 2, weight: 4, text: "AGREE", correct: nil},
  {question_id: 2, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 3, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 3, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 3, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 3, weight: 4, text: "AGREE", correct: nil},
  {question_id: 3, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 4, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 4, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 4, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 4, weight: 4, text: "AGREE", correct: nil},
  {question_id: 4, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 5, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 5, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 5, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 5, weight: 4, text: "AGREE", correct: nil},
  {question_id: 5, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 6, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 6, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 6, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 6, weight: 4, text: "AGREE", correct: nil},
  {question_id: 6, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 7, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 7, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 7, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 7, weight: 4, text: "AGREE", correct: nil},
  {question_id: 7, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 8, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 8, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 8, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 8, weight: 4, text: "AGREE", correct: nil},
  {question_id: 8, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 9, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 9, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 9, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 9, weight: 4, text: "AGREE", correct: nil},
  {question_id: 9, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 10, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 10, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 10, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 10, weight: 4, text: "AGREE", correct: nil},
  {question_id: 10, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 11, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 11, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 11, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 11, weight: 4, text: "AGREE", correct: nil},
  {question_id: 11, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 12, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 12, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 12, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 12, weight: 4, text: "AGREE", correct: nil},
  {question_id: 12, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 13, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 13, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 13, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 13, weight: 4, text: "AGREE", correct: nil},
  {question_id: 13, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 14, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 14, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 14, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 14, weight: 4, text: "AGREE", correct: nil},
  {question_id: 14, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 15, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 15, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 15, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 15, weight: 4, text: "AGREE", correct: nil},
  {question_id: 15, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 16, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 16, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 16, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 16, weight: 4, text: "AGREE", correct: nil},
  {question_id: 16, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 17, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 17, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 17, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 17, weight: 4, text: "AGREE", correct: nil},
  {question_id: 17, weight: 5, text: "STRONGLY AGREE", correct: nil},
  {question_id: 18, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 18, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 18, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 18, weight: 4, text: "AGREE", correct: nil},
  {question_id: 18, weight: 5, text: "STRONGLY AGREE", correct: nil},
  {question_id: 19, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 19, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 19, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 19, weight: 4, text: "AGREE", correct: nil},
  {question_id: 19, weight: 5, text: "STRONGLY AGREE", correct: nil},
  {question_id: 20, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 20, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 20, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 20, weight: 4, text: "AGREE", correct: nil},
  {question_id: 20, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 21, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 21, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 21, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 21, weight: 4, text: "AGREE", correct: nil},
  {question_id: 21, weight: 5, text: "STRONGLY AGREE", correct: nil},
  {question_id: 22, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 22, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 22, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 22, weight: 4, text: "AGREE", correct: nil},
  {question_id: 22, weight: 5, text: "STRONGLY AGREE", correct: nil},
  {question_id: 23, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 23, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 23, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 23, weight: 4, text: "AGREE", correct: nil},
  {question_id: 23, weight: 5, text: "STRONGLY AGREE", correct: nil},
  {question_id: 24, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 24, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 24, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 24, weight: 4, text: "AGREE", correct: nil},
  {question_id: 24, weight: 5, text: "STRONGLY AGREE", correct: nil},
   {question_id: 25, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 25, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 25, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 25, weight: 4, text: "AGREE", correct: nil},
  {question_id: 25, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 26, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 26, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 26, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 26, weight: 4, text: "AGREE", correct: nil},
  {question_id: 26, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 27, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 27, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 27, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 27, weight: 4, text: "AGREE", correct: nil},
  {question_id: 27, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 28, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 28, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 28, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 28, weight: 4, text: "AGREE", correct: nil},
  {question_id: 28, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 29, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 29, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 29, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 29, weight: 4, text: "AGREE", correct: nil},
  {question_id: 29, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 30, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 30, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 30, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 30, weight: 4, text: "AGREE", correct: nil},
  {question_id: 30, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 31, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 31, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 31, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 31, weight: 4, text: "AGREE", correct: nil},
  {question_id: 31, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 32, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 32, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 32, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 32, weight: 4, text: "AGREE", correct: nil},
  {question_id: 32, weight: 5, text: "STRONGLY AGREE", correct: nil},
   {question_id: 33, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 33, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 33, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 33, weight: 4, text: "AGREE", correct: nil},
  {question_id: 33, weight: 5, text: "STRONGLY AGREE", correct: nil},

   {question_id: 34, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 34, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 34, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 34, weight: 4, text: "AGREE", correct: nil},
  {question_id: 34, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 35, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 35, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 35, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 35, weight: 4, text: "AGREE", correct: nil},
  {question_id: 35, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 36, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 36, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 36, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 36, weight: 4, text: "AGREE", correct: nil},
  {question_id: 36, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 37, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 37, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 37, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 37, weight: 4, text: "AGREE", correct: nil},
  {question_id: 37, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 38, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 38, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 38, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 38, weight: 4, text: "AGREE", correct: nil},
  {question_id: 38, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 39, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 39, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 39, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 39, weight: 4, text: "AGREE", correct: nil},
  {question_id: 39, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 40, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 40, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 40, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 40, weight: 4, text: "AGREE", correct: nil},
  {question_id: 40, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 41, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 41, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 41, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 41, weight: 4, text: "AGREE", correct: nil},
  {question_id: 41, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 42, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 42, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 42, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 42, weight: 4, text: "AGREE", correct: nil},
  {question_id: 42, weight: 5, text: "STRONGLY AGREE", correct: nil},


  {question_id: 43, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 43, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 43, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 43, weight: 4, text: "AGREE", correct: nil},
  {question_id: 43, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 44, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 44, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 44, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 44, weight: 4, text: "AGREE", correct: nil},
  {question_id: 44, weight: 5, text: "STRONGLY AGREE", correct: nil},

  {question_id: 45, weight: 1, text: "STRONGLY DISAGREE", correct: nil},
  {question_id: 45, weight: 2, text: "DISAGREE", correct: nil},
  {question_id: 45, weight: 3, text: "NEUTRAL", correct: nil},
  {question_id: 45, weight: 4, text: "AGREE", correct: nil},
  {question_id: 45, weight: 5, text: "STRONGLY AGREE", correct: nil}
])
Survey::Question.create!([
  {survey_id: 1, text: "My team and the larger organization can clearly articulate the goals of the consulting team."},
  {survey_id: 1, text: "Our customers and our team would agree on our value proposition."},
  {survey_id: 1, text: "Our team's goals support the goals of the larger organization and are aligned with those of other departments (e.g. Sales, Marketing, Product Management)."},
  {survey_id: 1, text: "Marketing and Sales bring leads to the Services team that are appropriate to our role and value proposition."},
  {survey_id: 1, text: "Sales, Marketing, and Product Management work in partnership with Services to meet corporate objectives and customer needs."},
  {survey_id: 1, text: "Services leadership is an integral part of the executive team, providing leadership and direction at the corporate and departmental level."},
{survey_id: 2, text: "Services, Sales, and Marketing have defined a Go To Market strategy with measurable objectives."},
{survey_id: 2, text:"Market positioning and branding reflect the Services team's core purpose and value proposition."},
{survey_id: 2, text:"Our marketing tools support lead generation, prospecting, and closing, and include a web presence, datasheets, and calls to action."},
{survey_id: 2, text:"Marketing regularly executes lead generation campaigns that are aligned with the goals of the Services team."},
{survey_id: 2, text:"Sales and Services consistently collaborate on Sales-driven prospecting and Services-led scope/proposal development."},
{survey_id: 2, text:"Our backlog is manageable: Sales generates leads in balance with the Services team's capacity."},
{survey_id: 2, text:"Our team has completed a SWOT analysis (Strengths, Weaknesses, Opportunities, and Threats) and reviews it regularly to identify areas of strategic improvement."},
 {survey_id: 3, text:"The Services Portfolio contains a discrete set of service offerings defined and approved by Services leadership."},
 {survey_id: 3, text:"Our service offerings map directly to specific pains commonly felt by our target market."},
 {survey_id: 3, text:"The Services team has the necessary skills to deliver our service offerings at a high level of quality and profitability."},
 {survey_id: 3, text:"Services pricing aligns to the market and reflects our team's expertise, experience, and value creation."},
 {survey_id: 4, text:"Sales consistently sells services in accord with our established process."},
 {survey_id: 4, text:"Any deviation from the established sales process, or selling of services outside the services portfolio, is properly communicated to Services management."},
 {survey_id: 4, text:"Our knowledge management system includes the delivery tools and templates needed to execute services at a consistent level of quality."},
 {survey_id: 4, text:"Our project management practices enable on-time, on-budget project delivery and a high level of customer satisfaction."},
 {survey_id: 4, text:"Consultants and Project Managers communicate risk and escalate issues in a timely manner."},
 {survey_id: 4, text:"We use quantifiable metrics to identify \"At Risk\" projects and have a consistent method of tracking and managing them."},
 {survey_id: 4, text:"Our assessment processes indicate a high level of quality across consultants and project types."},
 {survey_id: 4, text:"We review each project at completion and communicate lessons learned throughout Services, Sales, Product Management, Marketing, and senior leadership as necessary."},
 {survey_id: 5, text:"We use a well-defined, well-executed New Hire Onboarding (NHO) program."},
 {survey_id: 5, text:"We measure the effectiveness of our NHO program."},
 {survey_id: 5, text:"We have a sufficient annual budget to train our staff and develop their skills."},
 {survey_id: 5, text:"We have sufficient time to train our staff and develop their skills."},
 {survey_id: 5, text:"We have a development program that supports those who want to follow a management track and those who want to follow a technical track."},
 {survey_id: 5, text:"Services team members do not need to leave the department or company to grow their skills, responsibilities, and salary."},
{survey_id: 5, text:"We actively use a skills matrix to ensure we have the right skills in house and can assign the people with the right skills to projects."},
{survey_id: 5, text:"Our skills matrix is used as a tool to discuss skills development with each team member."},
{survey_id: 5, text:"We provide a system for team members to capture important lessons learned, and incentivize doing so."},
{survey_id: 5, text:"Services team members develop their personal brands through thought leadership (writing, speaking, blogging, etc.)."},
{survey_id: 6, text:"The Key Performance Indicators (metrics) are reviewed regularly by Services management, Finance, and senior leadership and are strongly aligned with the goals and objectives of the Services team."},
{survey_id: 6, text:"Team members are empowered to make decisions but reach out to management for approval when required."},
{survey_id: 6, text:"A standard set of project- and practice-level reports are created and distributed regularly among project teams, the Services department, and the larger organization."},
{survey_id: 6, text:"Pre-approved contract templates exist and are routinely used for services work."},
{survey_id: 6, text:"The Services team always reviews and approves contracts for services offerings before they are sent to the customer."},
{survey_id: 6, text:"Our project/resource scheduling system allows us to assign resources in a timely manner after a customer signs a contract."},
{survey_id: 6, text:"Team members can see future work assignments as well as their active projects."},
{survey_id: 6, text:"Consultants have visibility into upcoming projects to which they are not assigned but for which they have skills that are needed."},
{survey_id: 6, text:"Team members are required and expected to submit records of time spent on projects and tasks, as well as expenses incurred at the project and practice level."},
{survey_id: 6, text:"The delivery project manager reviews and approves invoices before they are sent to customers, particularly for time and materials or milestone-based projects."}
])
Survey::Survey.create!([
  {name: "I", description: "Business Mission & Strategy", attempts_number: 0, finished: false, active: true, survey_type: 1},
  {name: "II", description: "Go To Market Strategy", attempts_number: 0, finished: false, active: true, survey_type: 1},
  {name: "III", description: "Services Portfolio", attempts_number: 0, finished: false, active: true, survey_type: 1},
  {name: "IV", description: "Repeatable Delivery Framework", attempts_number: 0, finished: false, active: true, survey_type: 1},
  {name: "V", description: "The Services Team", attempts_number: 0, finished: false, active: true, survey_type: 1},
  {name: "VI", description: "Business Operations & Financial Management", attempts_number: 0, finished: false, active: true, survey_type: 1}
])


User.create!([
  {name: "Andra", email: "andrastanciu212@gmail.com"}
])
